### ISSUE TITLE
Ares Directory

### ISSUE THREAD

**Issue by asarj** [Ethos-lab/ares#6]
Ares Directory

- [ ] 1. Following the custom reward definitions, I would add a reward/ directory with reward.py and default_reward.py (or something like time.py). This is future planning for when we have different reward types
- [ ] 2. For attacker agent, why is get_attack()  called every time attack() is called? Are there some stateful attacks that require the re_initialization every time? Why not create the attack as part of __init__?
- [ ] 3. Same comment as above, but for defender
- [ ] 4. For defender agent, I think change_classifier() should be renamed to policy() or defend())  due to future planned developments. Also, is there a reason it takes in index? It doesn't seem to use it in the environment.
     - Maybe have both functions in case defend() is externally needed for some preprocessing step. We could also just require that any defense components, even preprocessing ones, are part of the model's predict definition.

- [ ] 5. Along the same lines as above, I think the attack/defender should take in the env observation as part of their policy (i.e. attack()/policy())

**Comment by Adesoji1** [comment]
pls where are the resnet models?
